version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phpmyadmin
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
